// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVnBsHyyQwpUmmklh0ZEPJBqygkZq0k6M',
    appId: '1:973767795195:web:1435dccdfeff6f2d036b5e',
    messagingSenderId: '973767795195',
    projectId: 'webpick-111',
    authDomain: 'webpick-111.firebaseapp.com',
    databaseURL: 'https://webpick-111-default-rtdb.firebaseio.com',
    storageBucket: 'webpick-111.appspot.com',
    measurementId: 'G-YJTKS8LQ1Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMRbQ2gvFqyq4ADdxMMT1bmj5HJja-imU',
    appId: '1:973767795195:android:c7dde0fc7ffa88c9036b5e',
    messagingSenderId: '973767795195',
    projectId: 'webpick-111',
    databaseURL: 'https://webpick-111-default-rtdb.firebaseio.com',
    storageBucket: 'webpick-111.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFkq_4Tyyeenq1-VPOH4oUJ2mpIBvorU4',
    appId: '1:973767795195:ios:937fa8113965d517036b5e',
    messagingSenderId: '973767795195',
    projectId: 'webpick-111',
    databaseURL: 'https://webpick-111-default-rtdb.firebaseio.com',
    storageBucket: 'webpick-111.appspot.com',
    iosClientId: '973767795195-kdk9novf62g02r2lqhkeuomtua60450j.apps.googleusercontent.com',
    iosBundleId: 'com.example.webpick1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFkq_4Tyyeenq1-VPOH4oUJ2mpIBvorU4',
    appId: '1:973767795195:ios:937fa8113965d517036b5e',
    messagingSenderId: '973767795195',
    projectId: 'webpick-111',
    databaseURL: 'https://webpick-111-default-rtdb.firebaseio.com',
    storageBucket: 'webpick-111.appspot.com',
    iosClientId: '973767795195-kdk9novf62g02r2lqhkeuomtua60450j.apps.googleusercontent.com',
    iosBundleId: 'com.example.webpick1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVnBsHyyQwpUmmklh0ZEPJBqygkZq0k6M',
    appId: '1:973767795195:web:6b53d44d856248c1036b5e',
    messagingSenderId: '973767795195',
    projectId: 'webpick-111',
    authDomain: 'webpick-111.firebaseapp.com',
    databaseURL: 'https://webpick-111-default-rtdb.firebaseio.com',
    storageBucket: 'webpick-111.appspot.com',
    measurementId: 'G-GKJEN19F4H',
  );
}
